project:
  type: website
  execute-dir: project
  preview:
    port: 3456
  render:
    - "*.qmd"
    - "*.md"
    - "!etc/"
    - "!drafts/"
    #- "!documents/"
  resources:
    - "files/**"

pagetitle: "{{< meta title >}}"
author-meta: "Carl Colglazier"
brand: _brand.yml
website:
  title: "Carl Colglazier"
  open-graph: true
  site-url: "https://carlcolglazier.com"
  favicon: "assets/favicon.ico"
  navbar:
    pinned: false
    right:
      - text: "About"
        href: "index.qmd"
      - text: "Now"
        href: "now/index.qmd"
      - text: "Notes"
        file: "notes/index.qmd"
      - text: "Research"
        file: "research/index.qmd"
      #- text: "Code"
      #  file: "code/index.qmd"
  page-footer:
    center: |
      <span class="faux-block">{{< fa brands creative-commons >}} Carl Colglazier</span>
      <span class="faux-block">All content licensed under<br>[{{< fa brands creative-commons >}}{{< fa brands creative-commons-by >}}{{< fa brands creative-commons-nc >}}Creative Commons CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/)</span>
    right: |
      <span class="faux-block">Made with [Quarto{{< iconify simple-icons:quarto >}}](https://quarto.org/)</span>
      <span class="faux-block">View the source on [GitHub{{< fa brands github >}}](https://github.com/carlcolglazier/carlcolglazier.com)</span>
      <span class="hidden">{{< ai arxiv >}}</span>
    left:
    - text: "{{< iconify bi globe size=1.1em title='Website' >}}"
      href: "https://carlcolglazier.com"
      rel: "author"
      #class: "u-uid"
    - text: "{{< iconify bi envelope size=1.1em title='E-mail' >}}"
      href: "mailto:carlcolglazier+website@u.northwestern.edu"
    - text: "{{< iconify bi mastodon size=1.1em title='Mastodon' >}}"
      href: "https://hci.social/@carl"
      rel: "me"
    - text: "{{< iconify simple-icons:bluesky size=1.1em title='Bluesky' >}}"
      href: "https://bsky.app/profile/carl.cx"
      rel: "me"
    - text: "{{< iconify bi twitter size=1.1em title='Twitter' >}}"
      href: "https://twitter.com/carlcolglazier"
      rel: "me"
    - text: "{{< iconify bi github size=1.1em title='GitHub' >}}"
      href: "https://github.com/carlcolglazier"
      rel: "me"
    - text: "{{< iconify bi youtube size=1.1em title='YouTube' >}}"
      href: "https://www.youtube.com/carlcolglazier"
      rel: "me"

format:
  html:
    theme: [html/theme.scss, brand]
    #grid:
    #  margin-width: 250px
    #  body-width: 650px
    #  sidebar-width: 350px
    fig-width: 6
    toc: false
    code-link: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    include-in-header:
      - text: |
              <meta name="fediverse:creator" content="@carl@hci.social" />

execute:
  freeze: auto
