project:
  type: website
  #execute-dir: file
  preview:
    port: 3456
  render:
    - "*.qmd"
    - "*.md"
    - "!etc/"
  resources:
    - "files/**"

freeze: true
pagetitle: "{{< meta title >}} | Carl Colglazier"
author-meta: "Carl Colglazier"
website:
  title: "Carl Colglazier"
  open-graph: true
  site-url: "https://carlcolglazier.com"
  favicon: "assets/favicon.ico"
  navbar:
    pinned: false
    right:
      - text: "About"
        href: "index.qmd"
      - text: "Notes"
        file: "notes/index.qmd"
      - text: "Research"
        file: "research/index.qmd"
      - text: "Code"
        file: "code/index.qmd"
  page-footer:
    center: |
      <span class="faux-block">{{< fa brands creative-commons >}} Carl Colglazier</span>
      <span class="faux-block">All content licensed under<br>[{{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}} Creative Commons CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/)</span>
    right: |
      <span class="faux-block">Made with [Quarto](https://quarto.org/)</span>
      <span class="faux-block">[View the source at {{< fa brands github >}} GitHub](https://github.com/carlcolglazier/carlcolglazier.com)</span>
    left:
    - text: "{{< iconify bi globe size=1.1em title='Website' >}}"
      href: "https://carlcolglazier.com"
      rel: "author"
      #class: "u-uid"
    - text: "{{< iconify bi envelope size=1.1em title='E-mail' >}}"
      href: "mailto:carlcolglazier+website@u.northwestern.edu"
    - text: "{{< iconify bi mastodon size=1.1em title='Mastodon' >}}"
      href: "https://hci.social/@carl"
      rel: "me"
    - text: "{{< iconify bi twitter size=1.1em title='Twitter' >}}"
      href: "https://twitter.com/carlcolglazier"
      rel: "me"
    - text: "{{< iconify bi github size=1.1em title='GitHub' >}}"
      href: "https://github.com/carlcolglazier"
      rel: "me"
    - text: "{{< iconify bi youtube size=1.1em title='YouTube' >}}"
      href: "https://www.youtube.com/carlcolglazier"
      rel: "me"

format:
  html:
    theme: html/cc.scss
    grid:
      margin-width: 250px
      body-width: 650px
      sidebar-width: 350px
    fig-width: 6
    toc: false
    code-link: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true