baseurl: "https://carlcolglazier.com"
languageCode: "en-us"
title: "Carl Colglazier"
config: "config.yaml"
metaDataFormat: "yaml"
PygmentsCodeFences: true
paginate: 10
title: "Carl Colglazier"
languageCode: "en-us"
taxonomies:
  notes: "notes"
menu:
  main:
    - Name: "About"
      URL: "/about"
    - Name: "Notes"
      URL: "/notes"
      Weight: 0
    - Name: "Projects"
      URL: "/projects"
  featured:
    - Name: "Goals"
      URL: "/goals"
    - Name: "FAQs"
      URL: "/faqs"
blackfriday:
    plainIdAnchors: true
