baseurl: "https://carlcolglazier.com"
languageCode: "en-us"
title: "Carl Colglazier"
config: "config.yaml"
metaDataFormat: "yaml"
PygmentsCodeFences: true
pygmentsUseClasses: true
paginate: 10
title: "Carl Colglazier"
languageCode: "en-us"
menu:
  main:
    - name: "Home"
      url: "/"
      weight: -2
    - name: "Notes"
      url: "/notes"
      weight: 0
    - name: "Code"
      url: "/code"
      weight: -1
    - name: "Media"
      url: "/media"
      weight: -1
    - name: "Research"
      url: "/research"
      weight: -1
blackfriday:
    plainIdAnchors: true
privacy:
  instagram:
    disable: false
    simple: true
  twitter:
    disable: false
    enableDNT: true
    simple: true
  vimeo:
    disable: false
    simple: true
  youtube:
    disable: false
    privacyEnhanced: true
imaging:
  resampleFilter: "box"
  quality: 68
