baseurl: "https://carlcolglazier.com"
languageCode: "en-us"
title: "Carl Colglazier"
config: "config.yaml"
metaDataFormat: "yaml"
PygmentsCodeFences: true
paginate: 10
title: "Carl Colglazier"
languageCode: "en-us"
menu:
  main:
    - Name: "Notes"
      URL: "/notes"
      Weight: 0
    - Name: "Work"
      URL: "/work"
blackfriday:
    plainIdAnchors: true
