baseurl: "https://carlcolglazier.com"
languageCode: "en-us"
title: "Carl Colglazier"
config: "config.yaml"
metaDataFormat: "yaml"
paginate: 25
menu:
  main:
    - Name: "Notes"
      URL: "/notes"
      Weight: 0
  featured:
    - Name: "Goals"
      URL: "/goals"
    - Name: "Tools"
      URL: "/tools"
blackfriday:
    plainIdAnchors: true
