baseurl: "https://carlcolglazier.com"
languageCode: "en-us"
title: "Carl Colglazier"
config: "config.yaml"
metaDataFormat: "yaml"
PygmentsCodeFences: true
paginate: 10
title: "Carl Colglazier"
languageCode: "en-us"
taxonomies:
  notes: "notes"
menu:
  main:
    - Name: "Notes"
      URL: "/notes"
      Weight: 0
    - Name: "Publications"
      URL: "/publications"
# TODO: Document my open-source projects here.
#    - Name: "Projects"
#      URL: "/projects"
    - Name: "Oeuvre"
      URL: "/works"
blackfriday:
    plainIdAnchors: true
