baseurl: "https://carlcolglazier.com"
languageCode: "en-us"
title: "Carl Colglazier"
config: "config.yaml"
metaDataFormat: "yaml"
PygmentsCodeFences: true
paginate: 10
title: "Carl Colglazier"
languageCode: "en-us"
menu:
  main:
    - Name: "Notes"
      URL: "/notes"
      Weight: 0
    - Name: "Work"
      URL: "/work"
blackfriday:
    plainIdAnchors: true
privacy:
  instagram:
    disable: false
    simple: true
  twitter:
    disable: false
    enableDNT: true
    simple: true
  vimeo:
    disable: false
    simple: true
  youtube:
    disable: false
    privacyEnhanced: true
imaging:
  resampleFilter: "box"
  quality: 68
