#+STARTUP: indent hidestars
#+PROPERTY: header-args:R :session *R* :exports both :colnames yes :eval never-export :results value
#+hugo_section: notes
#+hugo_base_dir: ../
#+hugo_front_matter_format: yaml

* The Challenge of Content
This is a post about three things: cleaning, curves, and content.

Content is a catch-all term for media distributed through online
platforms. Many popular websites are now shared spaces that
essentially serve other people's stuff. It's a two-way relationship:
people publish where there are eyeball and readers don't want to miss
out on where everything is happening.

| Rank | Website      | Type            |
|------+--------------+-----------------|
|    1 | Google       | Search/services |
|    2 | YouTube      | Video           |
|    3 | Facebook     | Social          |
|    4 | Baidu        | Search          |
|    5 | Wikipedia    | Encyclopedia    |
|    6 | Reddit       | Aggregator      |
|    7 | Yahoo!       | Portal/media    |
|    8 | Tencent QQ   | Portal          |
|    9 | Taobao       | Shopping        |
|   10 | Google India | Search/services |

These spaces' allure comes from how they constantly serve something
fresh, media whose popularity generally follows a power law
probability distribution. In fact, if you graph the views for each of
my videos on this channel by the end of 2014 sorted by rank, the
distribution pretty closely matches Zipf's law, the value of the
maximum divided by the rank.

#+BEGIN_SRC R
#library("tuber")
#library("httr")
#yt_oauth("tidal-vim-196721", "AIzaSyBOWofPlp7toJ8shd98t8Kt-Ooe1z-5CGg")
https://www.googleapis.com/youtube/v3/search?key=AIzaSyBOWofPlp7toJ8shd98t8Kt-Ooe1z-5CGg&channelId=UCmdtMVA4uq2LJliikUCwNbQ&part=snippet,id&order=date&maxResults=20
#+END_SRC
